spring:
  application:
    name: gateway-service

server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8050

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
