spring:
  profiles:
    active: default

  application:
    name: gateway-service

  config:
    import: optional:configserver:http://localhost:9000

  cloud:
    config:
      label: main

  rabbitmq:
    host: ${rabbitmq.host}
    port: 5672
    username: guest
    password: guest

  jwt:
    secret: badfgkamsdgokmgweogsmaodgaoeirmgiofmdklhdfhhasfahdfvgohmeoagdfgmfomha

rabbitmq:
  host: localhost

management:
  endpoints:
    web:
      exposure:
        include: refresh,busrefresh


---
spring:
  config:
    activate:
      on-profile: live

    import: optional:configserver:http://55g-config-live:9000

---
spring:
  config:
    activate:
      on-profile: dev

    import: optional:configserver:http://55g-config-dev:9050