spring:
  application:
    name: gateway-service

server:
  port: 8000

eureka-server:
  host: localhost
  port: 8761
  postfix: default

eureka:
  user:
    name: admin
    password: 1234

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.user.name}:${eureka.user.password}@${eureka-server.host}:${eureka-server.port}/eureka

    registry-fetch-interval-seconds: 30

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: gateway,info,health

---
spring:
  config:
    activate:
      on-profile: live

eureka-server:
  postfix: live

---
spring:
  config:
    activate:
      on-profile: dev

eureka-server:
  port: 8762
  postfix: dev

server:
  port: 8050
---
spring:
  config:
    activate:
      on-profile: docker

eureka-server:
  host: 55g-eureka

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.user.name}:${eureka.user.password}@${eureka-server.host}-${eureka-server.postfix}:${eureka-server.port}/eureka