spring:
  profiles:
    active: default

  application:
    name: gateway-service

  config:
    import: optional:configserver:http://localhost:9000

  cloud:
    config:
      label: main

---
spring:
  config:
    activate:
      on-profile: live

    import: optional:configserver:http://55g-config-live:9000

---
spring:
  config:
    activate:
      on-profile: dev

    import: optional:configserver:http://55g-config-dev:9050