spring:
  application:
    name: gateway-service

server:
  port: 8000

eureka-server:
  host: localhost
  port: 8761
  postfix: default

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@${eureka-server.host}:${eureka-server.port}/eureka

  instance:
    prefer-ip-address: true

---
spring:
  config:
    activate:
      on-profile: live

eureka-server:
  postfix: live

---
spring:
  config:
    activate:
      on-profile: dev

eureka-server:
  port: 8762
  postfix: dev

server:
  port: 8050
---
spring:
  config:
    activate:
      on-profile: docker

eureka-server:
  host: 55g-eureka

eureka:
  client:
    service-url:
      defaultZone: http://admin:1234@${eureka-server.host}-${eureka-server.postfix}:${eureka-server.port}/eureka